### PR TITLE
individual challenge pages and highlights updated

### PR DESCRIPTION
**Pull request by burdinskid13**

### CODE REVIEW

**Comment by satra** [comment]
@burdinskid13 - let me know if this should be merged at this point, or wait for the formatting.

**Comment by burdinskid13** [comment]
individual challenges and highlights page final edits from debbie. 
two things still missing: 
1. additional therapy resources for the therapy challenge
2. formatting of the images on the highlights page (need a larger margin and some need cropping)

**Comment by danielmlow** [comment]
@burdinskid13 it's looking great. I'll fork your repo, make some edits and fix the image situation and then I'll do a PR. @satra you can close this PR

**Comment by satra** [comment]
@danielmlow - any updates on this?

**Comment by danielmlow** [comment]
> @danielmlow - any updates on this?

The challenge descriptions and images were added in this PR. A few descriptions needed some tuning and the images on the highlights page needed some cropping. 

I'll try to get back to this after the VFP paper is done.

**Pull request closed without merging**
